---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: artsy-wwwify-web
  namespace: default
  labels:
    app: artsy-wwwify
    component: web
    layer: application
spec:
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app: artsy-wwwify
      component: web
      layer: application
  template:
    metadata:
      labels:
        app: artsy-wwwify
        component: web
        layer: application
      name: artsy-wwwify-web
    spec:
      containers:
        - name: artsy-wwwify-web
          envFrom:
            - configMapRef:
                name: artsy-wwwify-environment
          image: 585031190124.dkr.ecr.us-east-1.amazonaws.com/artsy-wwwify:production
          imagePullPolicy: Always
          ports:
            - name: wwwify-http
              containerPort: 3000
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
            limits:
              memory: 1Gi
          readinessProbe:
            httpGet:
              port: wwwify-http
              path: /ping
            initialDelaySeconds: 2
            periodSeconds: 5
            timeoutSeconds: 5
      dnsPolicy: ClusterFirst
      dnsConfig:
        options:
          - name: ndots
            value: "1"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: tier
                  operator: In
                  values:
                    - foreground

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: artsy-wwwify-web
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: artsy-wwwify-web
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 70

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: artsy-wwwify
    component: web
    layer: application
  name: artsy-wwwify-web-internal
  namespace: default
spec:
  ports:
    - port: 3000
      protocol: TCP
      name: http
      targetPort: 3000
  selector:
    app: artsy-wwwify
    layer: application
    component: web
  type: ClusterIP

---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: artsy-wwwify
  annotations:
    nginx.ingress.kubernetes.io/whitelist-source-range: "{{ cloudflareIpSourceRanges|join(',') }}"
spec:
  ingressClassName: nginx
  rules:
    - host: artsy.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              serviceName: artsy-wwwify-web-internal
              servicePort: http
    - host: m.artsy.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              serviceName: artsy-wwwify-web-internal
              servicePort: http
    - host: ascii.artsy.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              serviceName: artsy-wwwify-web-internal
              servicePort: http
