---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: artsy-wwwify-web
  namespace: default
spec:
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: artsy-wwwify
        component: web
        layer: application
      name: artsy-wwwify-web
    spec:
      containers:
        - name: artsy-wwwify-web
          envFrom:
            - configMapRef:
                name: artsy-wwwify-environment
          image: 585031190124.dkr.ecr.us-east-1.amazonaws.com/artsy-wwwify:staging
          imagePullPolicy: Always
          ports:
            - name: wwwify-http
              containerPort: 3000
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
            limits:
              memory: 512Mi
          readinessProbe:
            httpGet:
              port: wwwify-http
              path: /ping
            initialDelaySeconds: 2
            periodSeconds: 5
            timeoutSeconds: 5
      dnsPolicy: ClusterFirst
      dnsConfig:
        options:
          - name: ndots
            value: "1"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: tier
                  operator: In
                  values:
                    - foreground

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: artsy-wwwify-web
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: artsy-wwwify-web
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 70

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: artsy-wwwify
    component: web
    layer: application
  name: artsy-wwwify-web
  namespace: default
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: {{ artsyNetWildcardSSLCert }}
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
    service.beta.kubernetes.io/aws-load-balancer-connection-draining-enabled: "true"
    service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "5"
spec:
  ports:
    - port: 80
      protocol: TCP
      name: http
      targetPort: wwwify-http
    - port: 443
      protocol: TCP
      name: https
      targetPort: wwwify-http
  selector:
    app: artsy-wwwify
    layer: application
    component: web
  sessionAffinity: None
  type: LoadBalancer
    - 173.245.48.0/20
    - 103.21.244.0/22
    - 103.22.200.0/22
    - 103.31.4.0/22
    - 141.101.64.0/18
    - 108.162.192.0/18
    - 190.93.240.0/20
    - 188.114.96.0/20
    - 197.234.240.0/22
    - 198.41.128.0/17
    - 162.158.0.0/15
    - 104.16.0.0/12
    - 172.64.0.0/13
    - 131.0.72.0/22
